### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by topden** [daemonforge/Dayz-HeroesAndBandits#2]
1. when warnings are displayed, for example, that he killed a zombie, then these warnings do not disappear, but hang on the screen constantly. can I make a timer on them? I can of course disable them in the config, but I just want them to light up for a short time.
I did not find the parameters in the config that would affect this
http://joxi.ru/L21G6wohgol0Or
if this parameter is responsible for this, then it does not work. set 1 sec and they still hang constantly
"NotificationMessageTime": 1,

2. and you can move them to the center of the screen and make a maximum of 2-3 lines of message, otherwise on the left they are very inhibited when you need to inspect the item and they overlap the item’s menu
http://joxi.ru/RmzoE6ZHRbEMD2
http://joxi.ru/Vm64ZwoijnLRgA

**Comment by DaemonF0rge** [comment]
So it seems you are using a older version of the expansion notification system, that was discontinued so that might be the issue, when I use notification system all I do is set the time through that, if there is issues with the notification staying past the time specified it sounds like an issue with your notification mod, I sadly can't support any discontinued mods sorry. Try with the native notification system and let me know if you still have the issues
Also try having a slightly longer time it's possible that having only one might cause an issue try 3 or 5 but that is only a guess

**Comment by topden** [comment]
Yes. you're right. The old version of the expansion notification system mod interfered with the normal operation of your mod. Thanks for the answer.
